In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [75]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report

In [21]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import RandomOverSampler

In [109]:
from sklearn.ensemble import GradientBoostingClassifier
import pydotplus
from IPython.display import Image

### Read the CSV and Perform Basic Data Cleaning

In [4]:
# https://help.lendingclub.com/hc/en-us/articles/215488038-What-do-the-different-Note-statuses-mean-

columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [58]:
# Load the data
file_path = Path('../Resources/LoanStats_2019Q1.csv.zip')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

#out_path = Path('../Resources/df_review.csv')
#df.to_csv(out_path)
df.head(-1)

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68811,10000.0,0.0646,306.31,MORTGAGE,98000.0,Source Verified,Jan-2019,low_risk,n,22.41,...,92.1,0.0,0.0,0.0,385928.0,28280.0,48800.0,57128.0,N,N
68812,10000.0,0.1502,346.76,RENT,26000.0,Source Verified,Jan-2019,low_risk,n,9.60,...,80.0,0.0,0.0,0.0,20625.0,6798.0,11300.0,5425.0,N,N
68813,12000.0,0.2727,368.37,RENT,63000.0,Not Verified,Jan-2019,low_risk,n,29.07,...,96.2,0.0,0.0,0.0,87939.0,60350.0,13500.0,62939.0,N,N
68814,5000.0,0.1992,185.62,MORTGAGE,52000.0,Source Verified,Jan-2019,low_risk,n,14.86,...,100.0,0.0,1.0,0.0,30592.0,18611.0,3600.0,18492.0,N,N
68815,40000.0,0.0646,1225.24,MORTGAGE,520000.0,Verified,Jan-2019,low_risk,n,9.96,...,98.2,12.5,0.0,0.0,1033574.0,95958.0,100800.0,78634.0,N,N

In [59]:
# Encode required data (converts str fields to float)
df_enc = pd.get_dummies(df, columns=['home_ownership','verification_status','issue_d','pymnt_plan','initial_list_status','next_pymnt_d','application_type','hardship_flag','debt_settlement_flag'])
df_enc.head()

,loan_amnt,int_rate,installment,annual_inc,loan_status,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,...,issue_d_Mar-2019,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
0,10500.0,0.1719,375.35,66000.0,low_risk,27.24,0.0,0.0,8.0,0.0,...,1,1,0,1,0,1,1,0,1,1
1,25000.0,0.2000,929.09,105000.0,low_risk,20.23,0.0,0.0,17.0,1.0,...,1,1,0,1,0,1,1,0,1,1
2,20000.0,0.2000,529.88,56000.0,low_risk,24.26,0.0,0.0,8.0,0.0,...,1,1,0,1,0,1,1,0,1,1
3,10000.0,0.1640,353.55,92000.0,low_risk,31.44,0.0,1.0,10.0,1.0,...,1,1,0,1,0,1,1,0,1,1
4,22000.0,0.1474,520.39,52000.0,low_risk,18.76,0.0,1.0,14.0,0.0,...,1,1,0,1,0,1,1,0,1,1

# Split the Data into Training and Testing

In [60]:
# Create features
X = df_enc.drop(columns='loan_status')

# Create target
y = df_enc['loan_status']

In [61]:
# Summary of features
X.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,issue_d_Mar-2019,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.0,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.0,68817.0
mean,16677.594562,0.127718,480.652863,8.821371e+04,21.778153,0.217766,0.497697,12.587340,0.126030,17604.142828,...,0.177238,1.0,0.123879,0.876121,0.383161,0.616839,0.860340,0.139660,1.0,1.0
std,10277.348590,0.048130,288.062432,1.155800e+05,20.199244,0.718367,0.758122,6.022869,0.336797,21835.880400,...,0.381873,0.0,0.329446,0.329446,0.486161,0.486161,0.346637,0.346637,0.0,0.0
min,1000.000000,0.060000,30.890000,4.000000e+01,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0
25%,9000.000000,0.088100,265.730000,5.000000e+04,13.890000,0.000000,0.000000,8.000000,0.000000,6293.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.0,1.0
50%,15000.000000,0.118000,404.560000,7.300000e+04,19.760000,0.000000,0.000000,11.000000,0.000000,12068.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.0,1.0
75%,24000.000000,0.155700,648.100000,1.040000e+05,26.660000,0.000000,1.000000,16.000000,0.000000,21735.000000,...,0.000000,1.0,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.0,1.0
max,40000.000000,0.308400,1676.230000,8.797500e+06,999.000000,18.000000,5.000000,72.000000,4.000000,587191.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0

In [62]:
# Balance of target values
y.value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [63]:
# Split the X and y into X_train, X_test, y_train, y_test
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

# Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble AdaBoost classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Print the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier onely, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [64]:
# Resample the training data with the RandomOversampler
ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
Counter(y_resampled)

Counter({'low_risk': 51366, 'high_risk': 51366})

In [101]:
# Create the random forest classifier instance
rf_model = RandomForestClassifier(n_estimators=100, random_state=1)

In [102]:
# Fit the model
rf_model = rf_model.fit(X_resampled, y_resampled)

In [103]:
# Making predictions using the testing data
predictions = rf_model.predict(X_test)

In [104]:
# Calculating the confusion matrix
cm = confusion_matrix(y_test, predictions)
cm_df = pd.DataFrame(
    cm, index=["Actual HR", "Actual LR"], columns=["Predicted HR", "Predicted LR"])
# Calculating the accuracy score
    #acc_score = accuracy_score(y_test, predictions)
bal_acc_score = balanced_accuracy_score(y_test, predictions)

In [105]:
# Displaying results
print("Confusion Matrix")
    #display(cm)
display(cm_df)
#print(f"Accuracy Score : {acc_score}")
print(f"Balanced Accuracy Score : {bal_acc_score}")
print("Classification Report")
print(classification_report_imbalanced(y_test, predictions))

Confusion Matrix

           Predicted HR  Predicted LR
Actual HR            31            70
Actual LR             7         17097

Balanced Accuracy Score : 0.653260716038863
Classification Report
                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.82      0.31      1.00      0.45      0.55      0.29       101
   low_risk       1.00      1.00      0.31      1.00      0.55      0.33     17104

avg / total       0.99      1.00      0.31      0.99      0.55      0.33     17205

In [106]:
# Feature importance array
importances = rf_model.feature_importances_

In [107]:
# Sorted features
importances_sorted = sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)
importances_sorted

[(0.08756236083272999, 'total_rec_prncp'),
 (0.06958377566542331, 'total_pymnt'),
 (0.06656675552831866, 'last_pymnt_amnt'),
 (0.06255817397079089, 'total_pymnt_inv'),
 (0.053850081774041325, 'total_rec_int'),
 (0.03368022250287762, 'issue_d_Jan-2019'),
 (0.029119886910001315, 'int_rate'),
 (0.02690980185978234, 'issue_d_Mar-2019'),
 (0.020289937769484134, 'installment'),
 (0.018833953631818428, 'out_prncp_inv'),
 (0.018405582474346243, 'out_prncp'),
 (0.01662676488029914, 'mths_since_recent_inq'),
 (0.015328722993950676, 'dti'),
 (0.01381965561707976, 'revol_bal'),
 (0.013776104116473585, 'total_bc_limit'),
 (0.013634571979526838, 'loan_amnt'),
 (0.013493158981293623, 'tot_hi_cred_lim'),
 (0.013261209182430329, 'avg_cur_bal'),
 (0.013178160477114209, 'max_bal_bc'),
 (0.012755151384788412, 'mo_sin_old_rev_tl_op'),
 (0.012589662696637853, 'annual_inc'),
 (0.012559506266333143, 'tot_cur_bal'),
 (0.012125416977617307, 'total_bal_ex_mort'),
 (0.011931988035728177, 'bc_open_to_buy'),
 (0.01187841542666181, 'all_util'),
 (0.011782045795594071, 'mo_sin_old_il_acct'),
 (0.011467637727776203, 'mths_since_rcnt_il'),
 (0.011365965175171546, 'total_bal_il'),
 (0.011273466413918371, 'il_util'),
 (0.01105304347072942, 'total_rev_hi_lim'),
 (0.01095913170005862, 'bc_util'),
 (0.010952894021440986, 'total_rec_late_fee'),
 (0.010896335894444229, 'issue_d_Feb-2019'),
 (0.010750029959353011, 'total_il_high_credit_limit'),
 (0.010233142306701963, 'mths_since_recent_bc'),
 (0.009376976530106036, 'next_pymnt_d_May-2019'),
 (0.008789531940466042, 'next_pymnt_d_Apr-2019'),
 (0.0087818225467835, 'total_acc'),
 (0.00861791097777317, 'num_rev_accts'),
 (0.008577567964040026, 'mo_sin_rcnt_rev_tl_op'),
 (0.008202892732613999, 'pct_tl_nvr_dlq'),
 (0.007828164272744815, 'num_op_rev_tl'),
 (0.007574512359933831, 'acc_open_past_24mths'),
 (0.007479988353822001, 'num_sats'),
 (0.007011407177034324, 'inq_last_12m'),
 (0.006982191958746477, 'num_il_tl'),
 (0.006589710933016912, 'total_cu_tl'),
 (0.006531797454299272, 'num_bc_tl'),
 (0.0062567939981959505, 'open_acc'),
 (0.006201530568203333, 'num_rev_tl_bal_gt_0'),
 (0.006201059518202768, 'percent_bc_gt_75'),
 (0.005997049858075657, 'num_actv_bc_tl'),
 (0.005968712865995593, 'mo_sin_rcnt_tl'),
 (0.0056321862043044535, 'open_act_il'),
 (0.005473678604531127, 'num_actv_rev_tl'),
 (0.005406237614784456, 'inq_fi'),
 (0.0051492952810751344, 'mort_acc'),
 (0.005093851748448529, 'num_tl_op_past_12m'),
 (0.004888819879116575, 'open_rv_24m'),
 (0.004887923059173031, 'open_acc_6m'),
 (0.0047829432239864045, 'open_il_24m'),
 (0.00467066468403363, 'num_bc_sats'),
 (0.0037299372066131537, 'inq_last_6mths'),
 (0.0033942320556075963, 'tot_coll_amt'),
 (0.00315544673488346, 'open_rv_12m'),
 (0.0028021827095576685, 'open_il_12m'),
 (0.0024877770908614803, 'delinq_2yrs'),
 (0.0024254878413306653, 'num_accts_ever_120_pd'),
 (0.0020752965810545577, 'verification_status_Not Verified'),
 (0.0017653347673148418, 'pub_rec_bankruptcies'),
 (0.0015492782816327775, 'verification_status_Verified'),
 (0.0014944129375727131, 'home_ownership_RENT'),
 (0.0014892962647676076, 'home_ownership_OWN'),
 (0.001444346910136158, 'initial_list_status_w'),
 (0.0013683288625769223, 'initial_list_status_f'),
 (0.0013340826410821532, 'home_ownership_MORTGAGE'),
 (0.0011590967142954837, 'pub_rec'),
 (0.0011171739637893632, 'application_type_Individual'),
 (0.0010413145745324973, 'verification_status_Source Verified'),
 (0.0008719618699070047, 'application_type_Joint App'),
 (0.0005955456652644405, 'num_tl_90g_dpd_24m'),
 (0.0005098604505109488, 'collections_12_mths_ex_med'),
 (0.00015042782009181825, 'home_ownership_ANY'),
 (3.0853639194891065e-05, 'chargeoff_within_12_mths'),
 (3.877071771723568e-07, 'delinq_amnt'),
 (0.0, 'tax_liens'),
 (0.0, 'recoveries'),
 (0.0, 'pymnt_plan_n'),
 (0.0, 'policy_code'),
 (0.0, 'num_tl_30dpd'),
 (0.0, 'num_tl_120dpd_2m'),
 (0.0, 'hardship_flag_N'),
 (0.0, 'debt_settlement_flag_N'),
 (0.0, 'collection_recovery_fee'),
 (0.0, 'acc_now_delinq')]

### Easy Ensemble AdaBoost Classifier

In [110]:
# Choose learning rate
learning_rates = [0.05, 0.1, 0.25, 0.5, 0.75, 1]
for learning_rate in learning_rates:
    model = GradientBoostingClassifier(
        n_estimators=100,
        learning_rate=learning_rate,
        max_features=2,
        max_depth=3,
        random_state=1)
    model.fit(X_train,y_train.ravel())
    print("Learning rate: ", learning_rate)

    # Score the model
    print("Accuracy score (training): {0:.3f}".format(
        model.score(
            X_train,
            y_train.ravel())))
    print("Accuracy score (validation): {0:.3f}".format(
        model.score(
            X_test,
            y_test.ravel())))
    print()

Learning rate:  0.05
Accuracy score (training): 0.996
Accuracy score (validation): 0.995

Learning rate:  0.1
Accuracy score (training): 0.997
Accuracy score (validation): 0.995

Learning rate:  0.25
Accuracy score (training): 0.996
Accuracy score (validation): 0.995

Learning rate:  0.5
Accuracy score (training): 0.769
Accuracy score (validation): 0.766

Learning rate:  0.75
Accuracy score (training): 0.819
Accuracy score (validation): 0.818

Learning rate:  1
Accuracy score (training): 0.666
Accuracy score (validation): 0.660

In [111]:
# Create GradientBoostingClassifier model based upon optimized learning rate
model = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=.1,
    max_features=5,
    max_depth=3,
    random_state=1)

# Fit the model
model.fit(X_train,y_train.ravel())

# Score the model
print("Accuracy score (training): {0:.3f}".format(
    model.score(
        X_train,
        y_train)))
print("Accuracy score (validation): {0:.3f}".format(
    model.score(
        X_test,
        y_test)))

Accuracy score (training): 0.996
Accuracy score (validation): 0.995

In [112]:
# Make predictions
predictions = model.predict(X_test)

# Generate accuracy score for predictions using y_test
balanced_accuracy_score(y_test, predictions)

0.6973766775648567

In [113]:
# Generatring the confusion matrix
cm = confusion_matrix(y_test, predictions)
cm_df = pd.DataFrame(
    cm, index=["Actual HR", "Actual LR"], columns=[
        "Predicted HR",
        "Predicted LR"
    ]
)

display(cm_df)

           Predicted HR  Predicted LR
Actual HR            40            61
Actual LR            22         17082

In [114]:
# Generate classification report
print(classification_report_imbalanced(y_test, predictions))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.65      0.40      1.00      0.49      0.63      0.37       101
   low_risk       1.00      1.00      0.40      1.00      0.63      0.42     17104

avg / total       0.99      1.00      0.40      0.99      0.63      0.42     17205

### Summary Results: All of the ensemble iterations produced poor (low) recall rates, which would be unacceptable from a lender's perspective. The best performer of the group was the Adaboost classifer as it had the highest recall rate at (40%) & a balance accuracy score ("BAC") of 69.7%. The Random Forest classifier had a decent precision rate, but recall was low, and a BAC of 65.3%.

### The top 3 features were 1) total principle received (total_rec_prncp), 2) total payment of principle & interest (total_pymnt) & 3) the amount of the last payment received (last_pymnt_amnt). The most intuitive is of the three is the total principle received, as it indicates the amount of capital the borrower has at risk & stands to loose if the loan is defaulted upon. Numbers two & three simply indicate a pattern of payment, i.e. if I received payment last month, I should receive payment this month. If I did not receie payment last month, I am less likely to receive payment this month.